# Generated by Django 3.0.6 on 2020-05-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
    ]
